#pragma once
#include "Plugin.h"

#define PLUGIN_NAME "MyPlugin"
#define PLUGIN_DESCRIPTION "My plugin description"
#define PLUGIN_AUTHOR "My name"
#define PLUGIN_VERSION_MAJOR 0
#define PLUGIN_VERSION_MINOR 1
#define PLUGIN_VERSION_PATCH 0
#define PLUGIN_VERSION_BUILD 0
#define PLUGIN_VERSION_STATUS Dev // Dev, Beta or Release
#define PLUGIN_VERSION_IS_RELEASE false
#define PLUGIN_VERSION_COMMIT_SHA Unknown
#define __TO_VERSION_STRING(ver) #ver
#define TO_VERSION_STRING(ver) __TO_VERSION_STRING(ver)
// clang-format off
#if PLUGIN_VERSION_BUILD > 0 && PLUGIN_VERSION_IS_RELEASE // Actions Build
#define PLUGIN_VERSION_STRING TO_VERSION_STRING(PLUGIN_VERSION_MAJOR.PLUGIN_VERSION_MINOR.PLUGIN_VERSION_PATCH-build.PLUGIN_VERSION_BUILD-PLUGIN_VERSION_COMMIT_SHA)
#elif PLUGIN_VERSION_BUILD > 0 && !PLUGIN_VERSION_IS_RELEASE // Actions Build
#define PLUGIN_VERSION_STRING TO_VERSION_STRING(PLUGIN_VERSION_MAJOR.PLUGIN_VERSION_MINOR.PLUGIN_VERSION_PATCH-PLUGIN_VERSION_STATUS-build.PLUGIN_VERSION_BUILD-PLUGIN_VERSION_COMMIT_SHA)
#elif PLUGIN_VERSION_BUILD == 0 && PLUGIN_VERSION_IS_RELEASE
#define PLUGIN_VERSION_STRING TO_VERSION_STRING(PLUGIN_VERSION_MAJOR.PLUGIN_VERSION_MINOR.PLUGIN_VERSION_PATCH)
#elif PLUGIN_VERSION_BUILD == 0 && !PLUGIN_VERSION_IS_RELEASE
#define PLUGIN_VERSION_STRING TO_VERSION_STRING(PLUGIN_VERSION_MAJOR.PLUGIN_VERSION_MINOR.PLUGIN_VERSION_PATCH-PLUGIN_VERSION_STATUS)
#endif
// clang-format on

#if PLUGIN_VERSION_IS_RELEASE
#define PLUGIN_FILE_VERSION_FLAG VS_FF_DEBUG
#else
#define PLUGIN_FILE_VERSION_FLAG 0x0L
#endif

#define FILE_VERSION_BLOCK_HEADER 0x04004B0L
#define FILE_VERSION_COMPANY_NAME PLUGIN_AUTHOR
#define FILE_VERSION_LEGAL_COPYRIGHT "Copyright " PLUGIN_AUTHOR " (c) 2023"
#define FILE_VERSION_FILE_DESCRIPTION PLUGIN_DESCRIPTION
#define FILE_VERSION_FILE_VERSION_STRING PLUGIN_VERSION_STRING
#define FILE_VERSION_INTERNAL_NAME PLUGIN_NAME
#define FILE_VERSION_ORIGINAL_FILENAME PLUGIN_NAME ".dll"
#define FILE_VERSION_PRODUCT_NAME FILE_VERSION_INTERNAL_NAME
#define FILE_VERSION_PRODUCT_VERSION_STRING PLUGIN_VERSION_STRING
#define FILE_VERSION_FILE_VERSION PLUGIN_VERSION_MAJOR, PLUGIN_VERSION_MINOR, PLUGIN_VERSION_PATCH, PLUGIN_VERSION_BUILD
#define FILE_VERSION_PRODUCT_VERSION FILE_VERSION_FILE_VERSION
